# Generated by Django 6.0.7 on 2026-08-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='folder',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
